### PR TITLE
.NET Standard 2.0 and asynchronous call support

### PR DESCRIPTION
**Pull request by halomakes**
- Enabled .NET Standard 2.0 support
- Added asynchronous equivalent for `PostSsoMember` (using `HttpClient`)
- Switch to BouncyCastle v1.8.3 (.NET Standard dist)

### CODE REVIEW

**Comment by markroland** [comment]
Thanks. I'll look this over this week.

**Comment by markroland** [comment]
We've looked this over and approved for merging. I will merge and then we will work on tagging it as a minor release (v1.3.0) since it includes your new async functionality. Thank you for contributing your code.

**Comment by dithidi** [comment]
Hi @halomademeapc, we are attempting to package this up for nuget and are running into some errors.  I keep getting the following:  

> Error NU5012: Unable to find 'bin/Debug/Abenity.Api/bin/Debug/'. Make sure the project has been built.

This is after I've restored the nuget packages and re ran the build successfully.

I've also attempted to run `nuget pack -Build` to build it before packaging and am seeing a different error that is stating that the project.assets.json doesn't have a target for .NETFramework,Version=v4.5.2 set up and to add net452 to the TargetFrameworks (which I've confirmed is already there from your PR).  Any advice on how to get this to package properly?

**Comment by halomakes** [comment]
I'm able to get it to pack by just right-clicking the project > Pack in VS 2017
Here's a copy of the output if that helps
https://1drv.ms/f/s!Aq4cCClBY4ZukKxBmyFu6sX7WrfygQ

**Comment by PorNazar** [comment]
Hi. @halomademeapc I'm trying to install Abenity package but I'm getting *Could not install package 'abenity-csharp 1.6.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.* Could you please tell me which framework version requires package or how to resolve this problem

**Comment by halomakes** [comment]
Hi @PorNazar 
With the 1.6.0 update, this package runs on .NET Standard 2.0, meaning you'll need at least .NET Framework 4.6.1 to use it.
You can see more about .NET Standard versioning and compatibility here: https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

You'll want to either update your project to at least .NET Framework 4.6.1 or use an older release of abenity-csharp if that is not an option for you.

**Comment by PorNazar** [comment]
Thank you @halomademeapc for such quick answer. But I tried to install package to program with .NET Framework 4.6.1 and get the same error. Do you know another options how to fix my Abenity package issue.
Capture

**Pull request merged**
